import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { CoachingComponent } from './coaching/coaching.component';
import { CoachingoffComponent } from './coachingoff/coachingoff.component';
import { AchievementsComponent } from './achievements/achievements.component';
import { AchievementsoffComponent } from './achievementsoff/achievementsoff.component';
import { FreecontentComponent } from './freecontent/freecontent.component';
import { ContentvitaminsComponent } from './contentvitamins/contentvitamins.component';
import { ContentsleepingComponent } from './contentsleeping/contentsleeping.component';
import { ContentworkouttypesComponent } from './contentworkouttypes/contentworkouttypes.component';
import { ContentworkoutComponent } from './contentworkout/contentworkout.component';
import { ContenthydrationComponent } from './contenthydration/contenthydration.component';
import { UserprofileComponent } from './userprofile/userprofile.component';
import { LoginComponent } from './login/login.component';
import { RecoverloginComponent } from './recoverlogin/recoverlogin.component';
import { ChangePasswordComponent } from './change-password/change-password.component';
import { SignupComponent } from './signup/signup.component';
import { AdminpanelComponent } from './adminpanel/adminpanel.component';
import { AboutComponent } from './about/about.component';
import { ContactsComponent } from './contacts/contacts.component';

export const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', component: HomeComponent },
  { path: 'coaching', component: CoachingComponent },
  { path: 'coachingoff', component: CoachingoffComponent },
  { path: 'achievements', component: AchievementsComponent },
  { path: 'achievementsoff', component: AchievementsoffComponent },
  { path: 'freecontent', component: FreecontentComponent },
  { path: 'contentvitamins', component: ContentvitaminsComponent },
  { path: 'contentsleeping', component: ContentsleepingComponent },
  { path: 'contentworkouttypes', component: ContentworkouttypesComponent },
  { path: 'contentworkout', component: ContentworkoutComponent },
  { path: 'contenthydration', component: ContenthydrationComponent },
  { path: 'userprofile', component: UserprofileComponent },
  { path: 'login', component: LoginComponent },
  { path: 'recoverlogin', component: RecoverloginComponent },
  { path: 'changePassword', component: ChangePasswordComponent },
  { path: 'signup', component: SignupComponent },
  { path: 'adminpanel', component: AdminpanelComponent },
  { path: 'about', component: AboutComponent },
  { path: 'contacts', component: ContactsComponent },
  { path: '**', component: HomeComponent },
];
